export global LKPalette {
    out property<color> background: #1e1e2e;
    out property<color> foreground: #cdd6f4;
    out property<color> alternate-background: #181825;
    out property<color> alternate-foreground: #cdd6f4;
    out property<color> control-background: #313244;
    out property<color> control-foreground: #cdd6f4;
    out property<color> accent-background: #89b4fa;
    out property<color> accent-foreground: #1e1e2e;
    out property<color> selection-background: #b4befe;
    out property<color> selection-foreground: #1e1e2e;
}