import { SelectionPanelItem } from "@ui/components/selection-panel/index.slint";
import { LKPalette } from "@ui/style/color-palette.slint";
import { HorizontalBox } from "std-widgets.slint";

component SelectedIndicator inherits Rectangle {
    width: 10px;
    background: LKPalette.accent-background;
    visible: false;
}

export component LKVerticalSelectionPanelItem inherits SelectionPanelItem {
    height: 30px;

    states [
        hovered-not-selected when !root.is-selected && root.has-hover: {
            root.background: LKPalette.background;
            selected-indicator.visible: false;
        }

        selected when root.is-selected: {
            root.background: LKPalette.background;
            selected-indicator.visible: true;
        }
    ]

    HorizontalLayout {
        alignment: LayoutAlignment.space-between;
        Rectangle {
            selected-indicator := SelectedIndicator {}
        }
        Rectangle {
            @children
        }
        Rectangle {}
    }
}