import { SelectionBarItem } from "@ui/components/selection-bar/selection-bar-item.slint";

export { SelectionBarItem }

export component VerticalSelectionBar inherits Rectangle {
    in-out property <int> active-selection-index;
    in property <LayoutAlignment> alignment;

    VerticalLayout {
        alignment: root.alignment;
        @children
    }
}

export component HorizontalSelectionBar inherits Rectangle {
    in-out property <int> active-selection-index;
    in property <LayoutAlignment> alignment;

    HorizontalLayout {
        alignment: root.alignment;
        @children
    }   
}