import { SelectionBarItem } from "@ui/components/selection-bar/selection-bar-item.slint";

export { SelectionBarItem }

export component VerticalSelectionBar inherits Rectangle {
    in-out property <int> active-selection-index;

    VerticalLayout {
        @children
    }
}

export component HorizontalSelectionBar inherits Rectangle {
    in-out property <int> active-selection-index;

    HorizontalLayout {
        @children
    }   
}