import "@assets/fonts/JetBrainsMono-Bold.ttf";
import "@assets/fonts/JetBrainsMono-BoldItalic.ttf";
import "@assets/fonts/JetBrainsMono-ExtraBold.ttf";
import "@assets/fonts/JetBrainsMono-ExtraBoldItalic.ttf";
import "@assets/fonts/JetBrainsMono-ExtraLight.ttf";
import "@assets/fonts/JetBrainsMono-ExtraLightItalic.ttf";
import "@assets/fonts/JetBrainsMono-Italic.ttf";
import "@assets/fonts/JetBrainsMono-Light.ttf";
import "@assets/fonts/JetBrainsMono-LightItalic.ttf";
import "@assets/fonts/JetBrainsMono-Medium.ttf";
import "@assets/fonts/JetBrainsMono-MediumItalic.ttf";
import "@assets/fonts/JetBrainsMono-Regular.ttf";
import "@assets/fonts/JetBrainsMono-SemiBold.ttf";
import "@assets/fonts/JetBrainsMono-SemiBoldItalic.ttf";
import "@assets/fonts/JetBrainsMono-Thin.ttf";
import "@assets/fonts/JetBrainsMono-ThinItalic.ttf";

import { Config } from "@ui/globals.slint";

import { PageView, PageViewItem } from "@ui/components/page-view/page-view.slint";

import { VerticalSelectionBar, SelectionBarItem } from "@ui/components/selection-bar/selection-bar.slint"; 

import { InstancesPage, ServersPage, AccountsPage, SettingsPage } from "@ui/pages/pages.slint";

export component MainWindow inherits Window {
    title: "LK Launcher";

    min-height: 500px;
    
    HorizontalLayout {
        sidebar := VerticalSelectionBar {
            width: 200px;
            alignment: LayoutAlignment.start; 
            
            for label[index] in [
                "Instances", 
                "Servers", 
                "Accounts", 
                "Settings"
            ]: SelectionBarItem {
                height: 50px;
                background: index == page-view.active-page-index ? #3a3a3a : #2c2c2c;
                Text {
                    font-family: "JetBrains Mono";
                    font-size: 18px;
                    font-weight: 500;
                    text: label;
                }
                activate => { page-view.active-page-index = index }
            }
        }

        page-view := PageView {
            min-width: 500px; 
            active-page-index: 0;

            for index in 4: PageViewItem {
                is-active: index == page-view.active-page-index;

                if index == 0: InstancesPage {}
                if index == 1: ServersPage {}
                if index == 2: AccountsPage {}
                if index == 3: SettingsPage {}
            }
        }
    }

    
}